import type { BookVoteStats, ReviewItem } from "./types";

export const MOCK_VOTE_STATS: BookVoteStats = {
  recommendPercent: 80,
  notRecommendPercent: 20,
};

export const MOCK_REVIEWS: ReviewItem[] = [
  {
    id: "1",
    user: { name: "문소희", profileUrl: "" },
    date: "2024.03.20",
    vote: "not-recommend",
    content: "주인공? 불쌍한 척 하는데 사실 답답함. 초반은 흥미롭지만 후반이 아쉬웠어요.",
    isSpoiler: false,
    isRevealed: true,
    likes: 26,
    isLikedByMe: true,
  },
  {
    id: "2",
    user: { name: "책벌레", profileUrl: "" },
    date: "2024.03.19",
    vote: "recommend",
    content: "결말에서 밝혀지는 남편의 진짜 정체가 너무 충격적이었습니다. 교환 독서로 완전 추천해요!",
    isSpoiler: true,
    isRevealed: false,
    likes: 40,
    isLikedByMe: false,
  },
  {
    id: "3",
    user: { name: "테스트유저", profileUrl: "" },
    date: "2024.03.02",
    vote: "not-recommend",
    content: "긴 글 테스트는\n하긴해야죠\n긴 글 테스트는\n하긴해야죠\n긴 글 테스트는\n하긴해야죠\n긴 글 테스트는\n하긴해야죠\n",
    isSpoiler: true,
    isRevealed: false,
    likes: 3,
    isLikedByMe: true,
  },
  {
    id: "4",
    user: { name: "김주옥", profileUrl: "" },
    date: "2025.03.19",
    vote: "recommend",
    content: "내 이름은 김주옥",
    isSpoiler: true,
    isRevealed: false,
    likes: 60,
    isLikedByMe: false,
  },
  {
    id: "5",
    user: { name: "조혜연", profileUrl: "" },
    date: "2024.05.10",
    vote: "not-recommend",
    content: "테스트 멘트 넣기 힘들다.",
    isSpoiler: false,
    isRevealed: true,
    likes: 80,
    isLikedByMe: true,
  },
  {
    id: "6",
    user: { name: "탁은혜", profileUrl: "" },
    date: "2024.10.20",
    vote: "recommend",
    content: "진짜 도파민 터진다",
    isSpoiler: true,
    isRevealed: false,
    likes: 100,
    isLikedByMe: false,
  },
];
