import { StyleSheet } from "react-native";
import { wheelItemHeight } from "./constants";

export const searchStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 18,
  },
  backButton: {
    width: 38,
    height: 38,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerTitle: {
    marginLeft: 6,
    color: "#513A11",
    fontSize: 27,
    fontWeight: "900",
  },
  searchWrap: {
    minHeight: 54,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: "#513A11",
    borderRadius: 9,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 20,
    paddingRight: 12,
    color: "#513A11",
    fontSize: 17,
    fontWeight: "700",
  },
  searchButton: {
    width: 54,
    height: 40,
    marginRight: 8,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FCF5D7",
  },
  filterRow: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 12,
  },
  filterChip: {
    flex: 1,
    minWidth: 0,
    height: 34,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#DDDDDD",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 4,
    backgroundColor: "#F2F2F2",
  },
  filterChipActive: {
    borderColor: "#E4A54E",
    backgroundColor: "#FCF5D7",
  },
  filterText: {
    flexShrink: 1,
    color: "#A68D63",
    fontSize: 12,
    fontWeight: "800",
  },
  filterTextActive: {
    color: "#513A11",
  },
  resultHeader: {
    minHeight: 42,
    paddingHorizontal: 20,
    paddingTop: 2,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  resultCount: {
    color: "#513A11",
    fontSize: 16,
    fontWeight: "800",
  },
  excludeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  excludeText: {
    color: "#D7D7D7",
    fontSize: 13,
    fontWeight: "700",
  },
  excludeTextActive: {
    color: "#A68D63",
  },
  listContent: {
    paddingTop: 8,
    paddingBottom: 48,
  },
  loadingMore: {
    alignItems: "center",
    paddingVertical: 20,
  },
  emptyListContent: {
    flexGrow: 1,
  },
  divider: {
    height: 1,
    backgroundColor: "#513A11",
    opacity: 0.85,
  },
  resultItem: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  bookImage: {
    borderRadius: 14,
    resizeMode: "contain",
  },
  bookInfo: {
    flex: 1,
    minWidth: 0,
    paddingRight: 34,
  },
  metaText: {
    color: "#513A11",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "800",
  },
  metaLabel: {
    fontWeight: "900",
  },
  heartButton: {
    position: "absolute",
    top: 18,
    right: 18,
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 36,
  },
  emptyTitle: {
    marginTop: 14,
    color: "#513A11",
    fontSize: 18,
    fontWeight: "900",
  },
  emptyText: {
    marginTop: 6,
    color: "#A68D63",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0005",
    paddingHorizontal: 28,
  },
  filterSheet: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    padding: 18,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  datePickerSheet: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    padding: 18,
    shadowColor: "#000000",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  filterSheetTitle: {
    marginBottom: 10,
    color: "#513A11",
    fontSize: 17,
    fontWeight: "900",
  },
  filterOption: {
    minHeight: 48,
    borderRadius: 10,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  filterOptionActive: {
    backgroundColor: "#FFFCF3",
  },
  filterOptionText: {
    color: "#6E5A38",
    fontSize: 15,
    fontWeight: "700",
  },
  filterOptionTextActive: {
    color: "#E4A54E",
    fontWeight: "900",
  },
  dateTargetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  dateTargetCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    backgroundColor: "#F5F1EA",
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dateTargetCardActive: {
    backgroundColor: "#FCF5D7",
  },
  dateTargetLabel: {
    color: "#A68D63",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 3,
  },
  dateTargetValue: {
    color: "#6E5A38",
    fontSize: 12,
    fontWeight: "900",
  },
  dateTargetTextActive: {
    color: "#513A11",
  },
  dateRangeSeparator: {
    color: "#A68D63",
    fontSize: 16,
    fontWeight: "900",
  },
  wheelPickerWrap: {
    height: wheelItemHeight * 5,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    position: "relative",
  },
  wheelSelectedBand: {
    position: "absolute",
    left: 0,
    right: 0,
    top: wheelItemHeight * 2,
    height: wheelItemHeight,
    borderRadius: 10,
    backgroundColor: "#FCF5D7",
  },
  wheelColumn: {
    flex: 1,
    height: wheelItemHeight * 5,
  },
  wheelColumnContent: {
    paddingVertical: wheelItemHeight * 2,
  },
  wheelItem: {
    height: wheelItemHeight,
    alignItems: "center",
    justifyContent: "center",
  },
  wheelItemText: {
    color: "#CBBCA2",
    fontSize: 13,
    fontWeight: "700",
  },
  wheelItemActive: {
    color: "#513A11",
    fontSize: 14,
    fontWeight: "900",
  },
  rangeBlock: {
    marginTop: 14,
  },
  rangeLabel: {
    marginBottom: 8,
    color: "#A68D63",
    fontSize: 13,
    fontWeight: "800",
  },
  rangeUnit: {
    color: "#513A11",
    fontSize: 13,
    fontWeight: "800",
  },
  pageInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pageInput: {
    flex: 1,
    height: 42,
    borderWidth: 1,
    borderColor: "#DCC9A5",
    borderRadius: 8,
    color: "#513A11",
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    backgroundColor: "#FFFCF3",
  },
  pageRangeSymbol: {
    color: "#A68D63",
    fontSize: 18,
    fontWeight: "900",
  },
  modalActionRow: {
    marginTop: 22,
    flexDirection: "row",
    gap: 10,
  },
  modalActionButton: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  modalResetButton: {
    backgroundColor: "#F2F2F2",
  },
  modalApplyButton: {
    backgroundColor: "#E4A54E",
  },
  modalResetText: {
    color: "#A68D63",
    fontSize: 14,
    fontWeight: "800",
  },
  modalApplyText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },
});
